#:kivy 2.0.0

<GridButtons>:
    cols: 5
    rows: 3

<DynamicButton>
    Button:
        size: root.size
        pos: root.pos
        text: str(root.display_text)
        on_press: root.on_press()

<GridManagerWidget>:
    GridButtons:
        size: root.size
        pos: root.pos

<GameWidget>:
    GridManagerWidget:
        size: root.size
        pos: root.pos

<LeftPanelWidget>
    BoxLayout:
		size: root.size
		pos: root.pos
        orientation: 'vertical'
        Button:
            text: 'character stats'
            size_hint_y: 0.2
        Button:
            text: 'details'
            size_hint_y: 0.5
        Button:
            text: 'idk fam'
            size_hint_y: 0.3

<CenterPanelWidget>
	size: root.size
	pos: root.pos
    orientation: 'vertical'
	ScrollableWidget:
    GridManagerWidget:
        size_hint_y: 0.3

<ScrollableWidget>
    Label:
        text: root.text
        font_size: 32
        text_size: self.width, None
        size_hint_y: None
        height: self.texture_size[1]

<RightPanelWidget>
    BoxLayout:
		size: root.size
		pos: root.pos
        orientation: 'vertical'
        Button:
            text: 'map'
            size_hint_y: 0.2
        Button:
            text: 'enemy details'
            size_hint_y: 0.5
        Button:
            text: 'idk fam'
            size_hint_y: 0.3


<GameContainer>:
    orientation: 'horizontal'
    LeftPanelWidget:
        size_hint_x: 0.2
    CenterPanelWidget:
        size_hint_x: 0.6
    RightPanelWidget:
        size_hint_x: 0.2