#:kivy 2.0.0

<DynamicStatBar>
    fill_bar: fill_bar
    orientation: 'vertical'
    Label:
        size_hint_y: 0.3
        text_size: self.size
        text: root.display_text
        halign: "left"
    FloatLayout:
        id: fill_bar
        Label:
            pos: root.pos
            canvas.before:
                Color:
                    rgb: root.background_color
                RoundedRectangle:
                    pos: root.pos
                    size: self.size
        Label:
            canvas.before:
                Color:
                    rgb: root.foreground_color
                RoundedRectangle:
                    pos: root.pos
                    size: root.current_size
        Label:
            text: root.display_value
            pos: root.pos

<CharacterStatBlockDisplay>
    size: root.size
    pos: root.pos
    orientation: 'vertical'

<DynamicButton>
    Button:
        size: root.size
        pos: root.pos
        text: str(root.display_text)
        on_press: root.on_press()

<ListScrollManager>
    size_hint_y: None
    height: self.minimum_height
    row_default_height: root.size[0] / 5
    cols:1

<KivyCharacterManager>
    list_scroll_manager: list_scroll_manager
    orientation: 'vertical'
    Button:
        text: root.display_text
        size_hint_y: 0.25
    ScrollView:
        ListScrollManager:
            id: list_scroll_manager

<GameContainer>:
    left_panel: left_panel
    right_panel: right_panel
    scrollable_widget: scrollable_widget
    grid_manager: grid_manager
    orientation: 'horizontal'
    LeftPanelWidget:
        id: left_panel
        size_hint_x: 0.2
        BoxLayout:
        	size: root.left_panel.size
        	pos: root.left_panel.pos
            orientation: 'vertical'
            Button:
                text: 'Party List'
                size_hint_y: 0.2
            CharacterStatBlockDisplay:
                size_hint_y: 0.2
            Button:
                text: 'details'
                size_hint_y: 0.3
            Button:
                text: 'idk fam'
                size_hint_y: 0.3
    CenterPanelWidget:
        size_hint_x: 0.6
        orientation: 'vertical'
        ScrollableWidget:
            id: scrollable_widget
        	Label:
                text: root.scrollable_widget.text
                font_size: 32
                text_size: self.width, None
                size_hint_y: None
                height: self.texture_size[1]
        GridManager:
            id: grid_manager
            size_hint_y: 0.3
            cols: 5
            rows: 3
    RightPanelWidget:
        id: right_panel
        size_hint_x: 0.2
        BoxLayout:
        	size: root.right_panel.size
        	pos: root.right_panel.pos
            orientation: 'vertical'
            KivyCharacterManager:
                size_hint_y: 0.2
            Button:
                text: 'enemy details'
                size_hint_y: 0.4
            Button:
                text: 'idk fam'
                size_hint_y: 0.3